### ISSUE TITLE
Not same results after reproducing the code

### ISSUE THREAD

**Issue by taugenichts** [sspringenberg/Speech-Aux-VAE#1]
Hello,

I tried to reproduce the code and got different results than shown in the Output Spectrogram and also in the paper.
After reading the paper and using the same the parameters I got this Spectogram for the vae_g_l model.
Did you used other parameters? Can you please share what values you used to get the same results as in the paper?
I also used the LibriSpeech Dataset.

![reconstruction_spec](https://user-images.githubusercontent.com/30925600/86768452-e712b880-c04d-11ea-8b12-61c20abb4125.png)

**Comment by martinBmeza** [comment]
do you find the proper way to replicate the paper results? @taugenichts
